// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


global.document = window.document;
global.window = window;

describe('LoginTests', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it("LoginRenderTest", async function () {
		// Test name: LoginRenderTest
		// Step # | name | target | value                                           
		// 1 | open | /login | 
		await driver.get("http://localhost:3000/login");
		// 3 | assertElementPresent | id=LoginContainer | 
		{
			const elements = await driver.findElements(By.id("LoginContainer"));
			assert(elements.length);
		}
		// 4 | assertElementPresent | id=username | 
		{
			const elements = await driver.findElements(By.id("username"));
			assert(elements.length);
		}
		// 5 | assertElementPresent | id=password | 
		{
			const elements = await driver.findElements(By.id("password"));
			assert(elements.length);
		}
		// 6 | assertElementPresent | id=btnLogin | 
		{
			const elements = await driver.findElements(By.id("btnLogin"));
			assert(elements.length);
		}
	});
  it('LoginSucess', async function() {
    // Test name: LoginSucess
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:3000/login")
    // 2 | setWindowSize | 945x1020 | 
    await driver.manage().window().setRect({ width: 945, height: 1020 })
    // 3 | type | id=username | chamfrado
    await driver.findElement(By.id("username")).sendKeys("chamfrado")
    // 4 | type | id=password | 123
    await driver.findElement(By.id("password")).sendKeys("123")
    // 5 | click | id=username | 
    await driver.findElement(By.id("username")).click()
    // 6 | click | id=btnLogin | 
    await driver.findElement(By.id("btnLogin")).click()
    // 7 | verifyElementPresent | id=ClienteContainer | 
    {
      const elements = await driver.findElements(By.id("ClienteContainer"))
      assert(elements.length)
    }
  })
  it('LoginIncorrect', async function() {
    // Test name: LoginIncorrect
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://localhost:3000/login")
    // 2 | setWindowSize | 945x1020 | 
    await driver.manage().window().setRect({ width: 945, height: 1020 })
    // 3 | type | id=username | lohran
    await driver.findElement(By.id("username")).sendKeys("lohran")
    // 4 | type | id=password | 4485
    await driver.findElement(By.id("password")).sendKeys("4485")
    // 5 | click | id=btnLogin | 
    await driver.findElement(By.id("btnLogin")).click()
    // 6 | verifyElementPresent | id=incorrectAlert | 
    {
      const elements = await driver.findElements(By.id("incorrectAlert"))
      assert(elements.length)
    }
  })
})
